#index:
#    path: /
#    controller: App\Controller\DefaultController::index

especialidades-index:
  path: /especialidades
  controller: App\Controller\EspecialidadeController::index
  methods:
    - GET

especialidades-store:
  path: /especialidades
  controller: App\Controller\EspecialidadeController::store
  methods:
    - POST

especialidades-show:
  path: /especialidades/{id}
  controller: App\Controller\EspecialidadeController::show
  methods:
    - GET

especialidades-show-medicos:
  path: /especialidades/{especialidadeId}/medicos
  controller: App\Controller\MedicoController::indexByEspecialidede
  methods:
    - GET

especialidades-update:
  path: /especialidades/{id}
  controller: App\Controller\EspecialidadeController::update
  methods:
    - PUT

especialidades-destroy:
  path: /especialidades/{id}
  controller: App\Controller\EspecialidadeController::destroy
  methods:
    - DELETE

medicos-index:
  path: /medicos
  controller: App\Controller\MedicoController::index
  methods:
    - GET

medicos-store:
  path: /medicos
  controller: App\Controller\MedicoController::store
  methods:
    - POST

medicos-show:
  path: /medicos/{id}
  controller: App\Controller\MedicoController::show
  methods:
    - GET

medicos-update:
  path: /medicos/{id}
  controller: App\Controller\MedicoController::update
  methods:
    - PUT

medicos-destroy:
  path: /medicos/{id}
  controller: App\Controller\MedicoController::destroy
  methods:
    - DELETE